language: python
python:
  - "2.7"
  - "2.6"
before_install:
  - pip install -U pip setuptools wheel pbr
install:
  - travis_wait pip install -r requirements.txt
  - travis_wait pip install -r test-requirements.txt

script:
  - python setup.py test -s zfec.test
notifications:
  email: false
  irc:
    channels: "chat.freenode.net#tahoe-lafs"
    on_success: always # for testing
    on_failure: always
    template:
      - "%{repository}#%{build_number} [%{branch}: %{commit} by %{author}] %{message}"
      - "Changes: %{compare_url} | Details: %{build_url}"
